version: '3.5'


# To Join any other app setup using another network, change name and set external = true
networks:
  default:
    name: kpm-qa
    external: false

secrets:
  # https://www.rockyourcode.com/using-docker-secrets-with-docker-compose/
  firebase_creds:
    file: ../credentials/keepem-d7092-firebase-adminsdk-us2h6-ac9154b389.json

volumes:
  mongo_db:
    name: kpm_mongo-qa
    external: true

services:
  mongo:
    container_name: mongo-qa
    hostname: mongo
    ports:
      - 127.0.0.1:2349:27017
    volumes:
      - mongo_db:/data/db

  api:
    container_name: api-qa
    env_file: kpm/.env.qa
    ports:
      - "127.0.0.1:2350:80"
  cron:
    container_name: cron-qa
    env_file: kpm/.env.qa
    environment:
      - FIREBASE_CREDENTIALS_FILE=/run/secret/firebase_creds
    secrets:
      - firebase_creds
    ports:
      - 127.0.0.1:2351:80