version: '3.5'


# To Join any other app setup using another network, change name and set external = true
networks:
  default:
    name: "kpm-dev"
    external: false

secrets:
  env_file:
    file: ./.env

volumes:
  mongo_db:
    name: kpm_mongo-dev
    external: true


services:
  mongo:
    container_name: mongo-dev
    hostname: mongo-dev
    image: mongo:5.0.8
    restart: unless-stopped
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'rs0',members:[{_id:0,host:\"mongo-dev:27017\"}]}).ok || rs.status().ok" | mongo --port 27017 --quiet) -eq 1
      interval: 10s
      start_period: 30s
    networks:
      - default
    ports:
      - "127.0.0.1:2299:27017"
    volumes:
      - mongo_db:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"

  api:
    container_name: api-dev
    build:
      context: .
    restart: unless-stopped
    env_file: kpm/.env.dev
    image: kpm-api
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
      - APP_MODULE=kpm.main:app
      - GUNICORN_CMD_ARGS=--forwarded-allow-ips *
      - "MONGODB_URL=mongodb://mongo-dev:27017/?replicaSet=rs0"
      - MAX_WORKERS=1
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"
    depends_on:
      - mongo
    ports:
      - "127.0.0.1:2300:80"
  cron:
    container_name: "cron-dev"
    build:
      context: .
    restart: unless-stopped
    env_file: "kpm/.env.dev"
    image: kpm-api
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
      - APP_MODULE=kpm.cron_app:app
      - GUNICORN_CMD_ARGS=--forwarded-allow-ips *
      - "MONGODB_URL=mongodb://mongo-dev:27017/?replicaSet=rs0"
      - MAX_WORKERS=1
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"
    depends_on:
      - mongo
    ports:
      - "127.0.0.1:2301:80"
