version: '3.5'


# To Join any other app setup using another network, change name and set external = true
networks:
  default:
    name: kpm-prod
    external: false

secrets:
  # https://www.rockyourcode.com/using-docker-secrets-with-docker-compose/
  firebase_creds:
    file: ../credentials/keepem-d7092-firebase-adminsdk-us2h6-ac9154b389.json

volumes:
  mongo_db:
    name: kpm_mongo-prod
    external: true

services:
  mongo:
    container_name: mongo-prod
    hostname: mongo
    ports:
      - 127.0.0.1:2399:27017
    volumes:
      - mongo_db:/data/db

  api:
    container_name: api-prod
    env_file: kpm/.env.prod
    environment:
      - MAX_WORKERS=24
    ports:
      - 127.0.0.1:2400:80
  cron:
    container_name: cron-prod
    env_file: kpm/.env.prod
    environment:
      - FIREBASE_CREDENTIALS_FILE=/run/secret/firebase_creds
    secrets:
      - firebase_creds
    ports:
      - 127.0.0.1:2401:80